### ISSUE TITLE
Don't work rightly on Ubuntu 16.04

### ISSUE THREAD

**Issue by seonghobae** [hironobu-s/swiftfs#3]
Hi there, 
I tried multiple trials with your code, but I can not do anything like this; 

```bash 
root @ login : ~ # curl -sL https://github.com/hironobu-s/swiftfs/archive/current .tar.gz | zcat> swiftfs && chmod + x swiftfs 
root @ login : ~ # ./swiftfs 
-bash : ./swiftfs : can not execute binary file : Exec format error 
``` 

How to solve this? Reply in the Japanese is okay. I can understand Japanese, but I can not type well in the PC environment.

Best
Seongho

**Comment by hironobu-s** [comment]
Hi @seonghobae 

I've not provided any binary packages.
Because Swiftfs has some bugs related the libraries this tool used. and I've not been able to fix it.

Thanks.

**Comment by seonghobae** [comment]
Hello again @ hironobu-s 

I just download and execute code what you provide, But it seems to change as binary. 
So that in current this software does not work well in current even I try to on CentOS? 

Best, 
Seongho

**Comment by hironobu-s** [comment]
Hi @seonghobae 

[In your post](https://github.com/hironobu-s/swiftfs/issues/3#issue-265502954), You specified the url as **https://github.com/hironobu-s/swiftfs/archive/current.tar.gz**. 

This file is source code archive file which provided from GitHub, not executable file.

If you need swiftfs binary, you can build it yourself. However, it may not work in latest version of Go.

Thanks

**Comment by seonghobae** [comment]
Okay, Finally I got the CloudFuse. CloudFuse so unstable, but I do not have any options. I hope the GMO guys are delivering official their native apps. Anyway, Thanks a lot!

Best,
Seongho
